# @name followTest
POST https://localhost:8080/follow
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyOTI0NzdhNjQtNDU0OS1iNmE5IiwiaWF0IjoxNzE2ODM1Mjg0LCJleHAiOjE3MTc0MzUyODR9.13j41_PxhKR-GuFyzNqCzwSZh-dLy2yPocn68hxoKro
eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyOTI0NzdhNjQtNDU0OS1iNmE5IiwiaWF0IjoxNzE2ODM1Mjg0LCJleHAiOjE3MTc0MzUyODR9.13j41_PxhKR-GuFyzNqCzwSZh-dLy2yPocn68hxoKro

{"follower": "user92477a64-4549-b6a9"  ,"followed": "user6393301c-42bb-8c19"}